feat: wip recording nodes
currently fails somewhere because I have an invalid path, i.e.,
ERROR: new row for relation "resource_node" violates check constraint
"valid_path" (SQLSTATE 23514)